const ADD_TODO = "ADD_TODO";
const INPUT_HANDLER = "INPUT_HANDLER";
const CHECKBOX_HANDLER = "CHECKBOX_HANDLER";
const DELETE_TODO = "DELETE_TODO";

export {ADD_TODO, INPUT_HANDLER, CHECKBOX_HANDLER, DELETE_TODO}